name: VANSOEST
favicon: null
layout_spectrum: 0.7571
typography_spectrum: 0.00417
title: VAN SOEST
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#f4f4f4'
    - '#2f2f2f'
    - '#909090'
    - '#b0b0b0'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
